spring:
  config:
    import:
      - classpath:database.yml
      - classpath:security.yml
      - classpath:awsS3.yml

springdoc:
  swagger-ui:
    path: /api-doc.html
  version: 'v1'
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  model-and-view-allowed: true
